// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR0RrUDiobanHNM12_qRqHgh8Y2Y15bTo',
    appId: '1:260376694479:web:c5da7c695c24bba904f1ba',
    messagingSenderId: '260376694479',
    projectId: 'ebuy-4f251',
    authDomain: 'ebuy-4f251.firebaseapp.com',
    storageBucket: 'ebuy-4f251.appspot.com',
    measurementId: 'G-WY7VEKC93E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDORSJ8DpMELAowoLBcDC86hMEnEIGFRlY',
    appId: '1:260376694479:android:8a23e4cf48f0d6c004f1ba',
    messagingSenderId: '260376694479',
    projectId: 'ebuy-4f251',
    storageBucket: 'ebuy-4f251.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3AnWrSyNVMFuddMrmkos-sexRuNElsDY',
    appId: '1:260376694479:ios:6fbb65e7468a05b304f1ba',
    messagingSenderId: '260376694479',
    projectId: 'ebuy-4f251',
    storageBucket: 'ebuy-4f251.appspot.com',
    iosBundleId: 'com.example.ebuy',
  );
}
